# Generated by Django 5.0.7 on 2024-07-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="phone",
            name="slug",
            field=models.SlugField(max_length=100),
        ),
    ]
